text = ""
text += "Hello there!\n"
text += "Right after launching this application you need to click 'Load from file'\n"
text += "Before you leave program you need to click 'Save to file'\n"
text += "\n"
text += "Structure of program:\n"
text += "Reservation:\n"
text += f'{" ":10}->Add new client\n'
text += f'{" ":10}->Add new school\n'
text += "Check:\n"
text += f'{" ":10}->Booking history\n'
text += f'{" ":10}->Financial raport\n'
text += "File:\n"
text += f'{" ":10}->Load to file\n'
text += f'{" ":10}->Save to file\n'
text += "Start screen:\n"
text += f'{" "*10}->Show start screen\n'
TEXT = text
