from PyQt5.QtCore import QMetaObject, QCoreApplication, Qt, QRect
from PyQt5.QtWidgets import QAction, QWidget, QVBoxLayout, QSplitter, QTextEdit, QMenuBar, QMenu, QStatusBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionAddReservation = QAction(MainWindow)
        self.actionAddReservation.setObjectName(u"actionAddReservation")
        self.actionAddReservation2 = QAction(MainWindow)
        self.actionAddReservation2.setObjectName(u"actionAddReservation")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionAddDate = QAction(MainWindow)
        self.actionAddDate.setObjectName(u"actionAddDate")
        self.actionAddDate2 = QAction(MainWindow)
        self.actionAddDate2.setObjectName(u"actionAddDate")
        self.actionShowStartScreen = QAction(MainWindow)
        self.actionShowStartScreen.setObjectName(u"actionShowStartScreen")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.View = QTextEdit(self.splitter)
        self.View.setObjectName(u"View")
        self.View.setReadOnly(True)
        self.splitter.addWidget(self.View)

        self.verticalLayout.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 50))
        self.menuReservation = QMenu(self.menubar)
        self.menuReservation.setObjectName(u"menuReservation")
        self.menuCheck = QMenu(self.menubar)
        self.menuCheck.setObjectName(u"menuCheck")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuStartScreen = QMenu(self.menubar)
        self.menuStartScreen.setObjectName(u"menumenuStartScreen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuReservation.menuAction())
        self.menubar.addAction(self.menuCheck.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStartScreen.menuAction())
        self.menuReservation.addAction(self.actionAddReservation)
        self.menuReservation.addAction(self.actionAddReservation2)
        self.menuCheck.addAction(self.actionAddDate)
        self.menuCheck.addAction(self.actionAddDate2)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuStartScreen.addAction(self.actionShowStartScreen)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SwimmingPool", None))
        self.actionAddReservation.setText(QCoreApplication.translate("MainWindow", u"Add new client", None))
        self.actionAddReservation2.setText(QCoreApplication.translate("MainWindow", u"Add new school", None))
        self.actionAddDate.setText(QCoreApplication.translate("MainWindow", u"Check booking history", None))
        self.actionAddDate2.setText(QCoreApplication.translate("MainWindow", u"Check financial raport", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load from files", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save to files", None))
        self.actionShowStartScreen.setText(QCoreApplication.translate("MainWindow", u"Show start screen", None))
        self.menuReservation.setTitle(QCoreApplication.translate("MainWindow", u"Reservation", None))
        self.menuCheck.setTitle(QCoreApplication.translate("MainWindow", u"Check", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuStartScreen.setTitle(QCoreApplication.translate("MainWindow", u"Start Screen", None))
